ecommerce_app/urls.py
from django.urls import path, include
from ecommerce_app import views

app_name = 'ecommerce_app'

urlpatterns = [
    path('', views.index, name='home' ),
    path('blog-single/<int:pk>/', views.blog_single, name='blog-single' ),
    path('blog/', views.blog, name='blog' ),
    path('contact/', views.contact, name='contact' ),
    path('product-detail/<int:pk>/', views.product_detail, name='product-detail' ),
    path('add-review/<int:id>/', views.add_review, name='add-review'),
    path('product/', views.product, name='product' ),
    path('cart/', views.cart, name='cart' ),
    path('home-two/', views.home_two, name='home-two' ),
    path('home-three/', views.home_three, name='home-three' ),
    path('add-to-cart/', views.add_to_cart, name='add-to-cart'),
    path('search/', views.search_view, name='search'),
    path('delete-from-cart/', views.delete_item_from_cart, name='delete-from-cart'),
    path('update-cart/', views.update_from_cart, name='update_cart'),
    path('checkout/<oid>', views.checkout, name='checkout'),
    path('shipping-address/', views.address, name='shipping-address'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('save_checkout_info/', views.save_checkout_info, name='save_checkout_info'),
    # Add to Wishlist
    path('add-to-wishlist/', views.add_to_wishlist, name='add-to-wishlist'),
    
    # Add to Wishlist
    path('delete-from-wishlist/', views.delete_wishlist, name='delete-from-wishlist'),


    
    #Paypal Url
    path('paypal/', include('paypal.standard.ipn.urls')),
    
     path('payment-completed/<oid>/', views.paypal_completed_view, name='payment-completed'),
     path('payment-failed/', views.paypal_failed_view, name='payment-failed'),


#Customer Dashboard URls

path('dashboard/', views.customer_dashboard, name='seller_dashboard'),     
path('order-detail/<int:pk>/', views.order_detail, name='order-detail'),     
path('shipping-address/', views.address, name='shipping-address'),
path('chart/', views.chart, name='chart'),
    
    
    

    

]

urls.py
from django.contrib import admin
from django.urls import path, include
from ecommerce_app import views
from django.conf import settings  
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import set_language
from django.conf.urls.static import static  
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include('ecommerce_app.urls', namespace='ecommerce_app')),
      path('', include('userauth.urls', namespace='userauth')),
      path('', include('selleradmin.urls', namespace='selleradmin')),
  

]

urlpatterns += i18n_patterns(
    # your other urls
     
      path('i18n/setlang/', set_language, name='set_language'),
)
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)  

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  

userauth/urls.py
from django.urls import path
from userauth import views

app_name = 'userauth'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('change_password/', views.change_password, name='change_password'),

]

templates/change_password.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
	<title>Change Password</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="{% static 'files/users/css/style.css' %}">

</head>

<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Change Password</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-12 col-lg-10">
					<div class="wrap d-md-flex">
						<div class="text-wrap p-4 p-lg-5 text-center d-flex align-items-center order-md-last">
							<div class="text w-100">
								<div class="icon"><span class=" fa fa-solid fa-user"></span></div>
								<h2>Change Password</h2>
								{% comment %} <p>Don't have an account?</p> {% endcomment %}
								{% comment %} <a href="{% url 'userauth:signup' %}" class="btn btn-white btn-outline-white">Sign
									Up</a> {% endcomment %}
							</div>
						</div>
						<div class="login-wrap p-4 p-md-5">
							<h3 class="mb-4">Hello! <span>Please login to continue</span></h3>
							{% if messages %}
							{% for message in messages %}
							<div class="alert {{message.tags}}">{{message}}</div>
							{% endfor %}

							{% endif %}

							<form action="#" method="POST" class="signup-form">
								{% csrf_token %}


								
								<div class="form-group">
									<label for="exampleInputPassword1">Old Password</label>
									<input type="password" name='old_password' class="form-control" id="password"
										placeholder="Password">
								</div>
								<div class="form-group">
									<label for="exampleInputPassword1">New Password</label>
									<input type="password" name='new_password' class="form-control" id="password"
										placeholder="Password">
								</div>
								<div class="form-group">
									<label for="exampleInputPassword1">Confirm Password</label>
									<input type="password" name='confirm_password' class="form-control" id="password"
										placeholder="Password">
								</div>
								<div class="form-group">
									<input type="checkbox" id="show-password">
									<label for="show-password">Show Password</label>
								</div>

								<div class="form-group">
									<button type="submit" class="btn btn-primary rounded submit p-3">Change Password</button>
								</div>
							</form>
							<div class="w-100 social-wrap">

								<p class="mt-4"><a href="{% url 'ecommerce_app:home' %}">Back to Home Page</a>
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

<script src="{% static 'files/users/js/jquery.min' %}"></script>
	<script src="{% static 'files/users/js/popper' %}"></script>
	<script src="{% static 'files/users/js/bootstrap.min' %}"></script>
	<script src="{% static 'files/users/js/main' %}"></script>

	<script>
		// Toggle password visibility
		document.getElementById('show-password').addEventListener('change', function () {
			var passwordInput = document.getElementById('password');
			if (passwordInput.type === 'password') {
				passwordInput.type = 'text';
			} else {
				passwordInput.type = 'password';
			}
		});
	</script>
</body>

</html>

templates/contact.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Contact US Page

{% endblock title %}

{% block content %}

<!-- Page Header Start -->
    <div class="container-fluid bg-secondary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
            <h1 class="font-weight-semi-bold text-uppercase mb-3">Contact Us</h1>
            <div class="d-inline-flex">
                <p class="m-0"><a href="">Home</a></p>
                <p class="m-0 px-2">-</p>
                <p class="m-0">Contact</p>
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Contact Start -->
    <div class="container-fluid pt-5">
        <div class="text-center mb-4">
            <h2 class="section-title px-5"><span class="px-2">Contact For Any Queries</span></h2>
        </div>
        <div class="row px-xl-5">
            <div class="col-lg-7 mb-5">
                <div class="contact-form">
                    <div id="success"></div>
                    <form  novalidate="novalidate" method="POST" action="{% url 'ecommerce_app:contact' %}">
                       {% csrf_token %}

                       {{ contact.as_p }}
                        <div>
                            <button class="btn btn-primary py-2 px-4" type="submit" >Send
                                Message</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-5 mb-5">
                <h5 class="font-weight-semi-bold mb-3">Get In Touch</h5>
                <p>Justo sed diam ut sed amet duo amet lorem amet stet sea ipsum, sed duo amet et. Est elitr dolor elitr erat sit sit. Dolor diam et erat clita ipsum justo sed.</p>
                <div class="d-flex flex-column mb-3">
                    <h5 class="font-weight-semi-bold mb-3">Store 1</h5>
                    <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                    <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                    <p class="mb-2"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
                </div>
                <div class="d-flex flex-column">
                    <h5 class="font-weight-semi-bold mb-3">Store 2</h5>
                    <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                    <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                    <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->

{% endblock content %}

templates/contact_us_template.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    <h4>Dear Admin</h4>

    <p>
        Name: {{name}}
        Email: {{email}}
    </p>

    <p>{{message}}</p>

</body>

</html>

templates/create-account.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
	<title>Ecommerce Sign Up Form</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="{% static 'files/users/css/style.css' %}">

</head>

<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">CREATE AN ACCOUNT </h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-12 col-lg-10">
					<div class="wrap d-md-flex">
						<div class="text-wrap p-4 p-lg-5 text-center d-flex align-items-center order-md-last">
							<div class="text w-100">
              
								<div class="icon"><span class=" fa fa-solid fa-user"></span></div>
								<h2>E-Shopper</h2>
								<p>Already have an account?</p>
                
                
								<a href="" class="btn btn-white btn-outline-white">Sign In</a>
							</div>
						</div>
						<div class="login-wrap p-4 p-md-5">
							<h3 class="mb-4">Hello! <span>Please signup to continue</span></h3>
							{% if form.errors %}
							<div class="alert alert-danger" role="alert">
								<ul>
									{% for field, errors in form.errors.items %}
									{% for error in errors %}
									<li>{{ error }}</li>
									{% endfor %}
									{% endfor %}
								</ul>

							</div>
							{% endif %}
							<form action="#" method="POST" class="signup-form">
								{% csrf_token %}

				          {{form.as_p}}
						
								<div class="form-group">
									<button type="submit" class="btn btn-primary rounded submit p-3">Sign Up</button>
								</div>
							</form>
							<div class="w-100 social-wrap">

								<p class="mt-4">I'm already a member! <a href="{% url 'userauth:login' %}">Sign In</a>
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<script src="{% static 'files/users/js/jquery.min' %}"></script>
	<script src="{% static 'files/users/js/popper' %}"></script>
	<script src="{% static 'files/users/js/bootstrap.min' %}"></script>
	<script src="{% static 'files/users/js/main' %}"></script>

</body>

</html>

templates/login.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
	<title>Sign Up 03</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="{% static 'files/users/css/style.css' %}">

</head>

<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">LOGIN</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-12 col-lg-10">
					<div class="wrap d-md-flex">
						<div class="text-wrap p-4 p-lg-5 text-center d-flex align-items-center order-md-last">
							<div class="text w-100">
								<div class="icon"><span class=" fa fa-solid fa-user"></span></div>
								<h2>Ecommerce App Login</h2>
								{% comment %} <p>Don't have an account?</p> {% endcomment %}
								{% comment %} <a href="{% url 'userauth:signup' %}" class="btn btn-white btn-outline-white">Sign
									Up</a> {% endcomment %}
							</div>
						</div>
						<div class="login-wrap p-4 p-md-5">
							<h3 class="mb-4">Hello! <span>Please login to continue</span></h3>
							{% if messages %}
							{% for message in messages %}
							<div class="alert {{message.tags}}">{{message}}</div>
							{% endfor %}

							{% endif %}

							<form action="#" method="post" class="signup-form">
								{% csrf_token %}


								<div class="form-group">
									<label for="exampleInputEmail1">Email</label>
									<input type="text" name='email' class="form-control" id="exampleInputEmail1"
										aria-describedby="emailHelp" placeholder="Enter Email">
								</div>
								<div class="form-group">
									<label for="exampleInputPassword1">Password</label>
									<input type="password" name='password' class="form-control" id="password"
										placeholder="Password">
								</div>
								<div class="form-group">
									<input type="checkbox" id="show-password">
									<label for="show-password">Show Password</label>
								</div>

								<div class="form-group">
									<button type="submit" class="btn btn-primary rounded submit p-3">Login</button>
								</div>
							</form>
							<div class="w-100 social-wrap">

								<p class="mt-4">Don't have an account?<a href="{% url 'userauth:signup' %}">Sign Up</a>
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

<script src="{% static 'files/users/js/jquery.min' %}"></script>
	<script src="{% static 'files/users/js/popper' %}"></script>
	<script src="{% static 'files/users/js/bootstrap.min' %}"></script>
	<script src="{% static 'files/users/js/main' %}"></script>

	<script>
		// Toggle password visibility
		document.getElementById('show-password').addEventListener('change', function () {
			var passwordInput = document.getElementById('password');
			if (passwordInput.type === 'password') {
				passwordInput.type = 'text';
			} else {
				passwordInput.type = 'password';
			}
		});
	</script>
</body>

</html>

templates/wishlist.html
{% extends 'base.html' %}

{% load static %}

{% block title %}

{% endblock title %}

{% block content %}

<div id="wishlist-list">
<!-- Page Header Start -->
<div class="container-fluid bg-secondary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
        <h1 class="font-weight-semi-bold text-uppercase mb-3">Wishlist</h1>
        <div class="d-inline-flex">
            <p class="m-0"><a href="">Home</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0">Wishlist</p>
        </div>
    </div>
</div>
<!-- Page Header End -->


<!-- Shop Start -->
<div class="container-fluid pt-5">
    <div class="row px-xl-5">
        <!-- Shop Sidebar Start -->
        {% comment %} <div class="col-lg-3 col-md-12 disabled">
            <!-- Price Start -->
            <div class="border-bottom mb-4 pb-4">
                <h5 class="font-weight-semi-bold mb-4">Filter by price</h5>
                <form>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" checked id="price-all">
                        <label class="custom-control-label" for="price-all">All Price</label>
                        <span class="badge border font-weight-normal">1000</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="price-1">
                        <label class="custom-control-label" for="price-1">$0 - $100</label>
                        <span class="badge border font-weight-normal">150</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="price-2">
                        <label class="custom-control-label" for="price-2">$100 - $200</label>
                        <span class="badge border font-weight-normal">295</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="price-3">
                        <label class="custom-control-label" for="price-3">$200 - $300</label>
                        <span class="badge border font-weight-normal">246</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="price-4">
                        <label class="custom-control-label" for="price-4">$300 - $400</label>
                        <span class="badge border font-weight-normal">145</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between">
                        <input type="checkbox" class="custom-control-input" id="price-5">
                        <label class="custom-control-label" for="price-5">$400 - $500</label>
                        <span class="badge border font-weight-normal">168</span>
                    </div>
                </form>
            </div>
            <!-- Price End -->

            <!-- Color Start -->
            <div class="border-bottom mb-4 pb-4">
                <h5 class="font-weight-semi-bold mb-4">Filter by color</h5>
                <form>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" checked id="color-all">
                        <label class="custom-control-label" for="price-all">All Color</label>
                        <span class="badge border font-weight-normal">1000</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="color-1">
                        <label class="custom-control-label" for="color-1">Black</label>
                        <span class="badge border font-weight-normal">150</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="color-2">
                        <label class="custom-control-label" for="color-2">White</label>
                        <span class="badge border font-weight-normal">295</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="color-3">
                        <label class="custom-control-label" for="color-3">Red</label>
                        <span class="badge border font-weight-normal">246</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="color-4">
                        <label class="custom-control-label" for="color-4">Blue</label>
                        <span class="badge border font-weight-normal">145</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between">
                        <input type="checkbox" class="custom-control-input" id="color-5">
                        <label class="custom-control-label" for="color-5">Green</label>
                        <span class="badge border font-weight-normal">168</span>
                    </div>
                </form>
            </div>
            <!-- Color End -->

            <!-- Size Start -->
            <div class="mb-5">
                <h5 class="font-weight-semi-bold mb-4">Filter by size</h5>
                <form>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" checked id="size-all">
                        <label class="custom-control-label" for="size-all">All Size</label>
                        <span class="badge border font-weight-normal">1000</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="size-1">
                        <label class="custom-control-label" for="size-1">XS</label>
                        <span class="badge border font-weight-normal">150</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="size-2">
                        <label class="custom-control-label" for="size-2">S</label>
                        <span class="badge border font-weight-normal">295</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="size-3">
                        <label class="custom-control-label" for="size-3">M</label>
                        <span class="badge border font-weight-normal">246</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="size-4">
                        <label class="custom-control-label" for="size-4">L</label>
                        <span class="badge border font-weight-normal">145</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between">
                        <input type="checkbox" class="custom-control-input" id="size-5">
                        <label class="custom-control-label" for="size-5">XL</label>
                        <span class="badge border font-weight-normal">168</span>
                    </div>
                </form>
            </div>
            <!-- Size End -->
        </div> {% endcomment %}
        <!-- Shop Sidebar End -->

        <!-- Shop Product Start -->
        <div class="col-lg-12 col-md-12">
            <div class="row pb-3">
                <div class="col-12 pb-1">
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        {% comment %} <form action="{% url 'ecommerce_app:search' %}" method="GET">

                            <div class="input-group">
                                <input type="text" class="form-control" name="q" value="{{ query }}"
                                    placeholder="Search by name">
                                <button type="submit" class="input-group-append">
                                    <span class="input-group-text bg-transparent text-primary">
                                        <i class="fa fa-search"></i>
                                    </span>
                                </button>
                            </div>
                        </form> {% endcomment %}
                        <div class="dropdown ml-4">
                            <button class="btn border dropdown-toggle" type="button" id="triggerId"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Sort by
                            </button>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="triggerId">
                                <a class="dropdown-item" href="#">Latest</a>
                                <a class="dropdown-item" href="#">Popularity</a>
                                <a class="dropdown-item" href="#">Best Rating</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% for w in wishlist %}
                <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                    <div class="card product-item border-0 mb-4">
                        <div
                            class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                            <img class="img-fluid w-100" src="{{w.product.image.url}}" alt="">
                        </div>
                        <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                            <h6 class="text-truncate mb-3">{{w.product.name}}</h6>
                            <div class="d-flex justify-content-center">
                                <h6>&#8358;{{w.product.price}}</h6>
                                <h6 class="text-muted ml-2"><del>$123.00</del></h6>
                            </div>
                        </div>
                        <div class="card-footer d-flex justify-content-between bg-light border">
                            <a href="{% url 'ecommerce_app:product-detail' w.product.id %}"
                                class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View
                                Detail</a>
                                 <button  class="btn border add-to-wishlist" data-product-item="{{w.product.id}}">
                    <i class="fas fa-heart text-primary"></i>
                    </button> 
                            <button class="btn btn-sm text-dark p-0 add-to-cart-btn" id=""
                                data-index="{{w.product.id}}"><i class="fas fa-shopping-cart text-primary mr-1"></i>Add
                                To Cart</button>
                                <button class="btn btn-sm btn-primary delete-wishlist" data-wishlist-product="{{w.id}}" ><i class="fa fa-times"></i></button>
                        </div>
                        <form action="">
                            {% csrf_token %}
                            <input id="product-id-{{w.product.id}}" class="product-id" type="hidden"
                                value="{{w.product.id}}">
                            <input id="product-quantity-{{w.product.id}}" class="product-quantity" type="hidden"
                                value="1">
                            <input id="product-title-{{w.product.id}}" class="product-title" type="hidden"
                                value="{{w.product.name}}">
                            <input id="product-price-{{w.product.id}}" class="product-price" type="hidden"
                                value="{{w.product.price}}">
                            <input id="product-image-{{w.product.id}}" class="product-image" type="hidden"
                                value="{{ w.product.image.url }}">
                        </form>

                    </div>
                </div>
                {% endfor %}

             
            </div>
        </div>
        <!-- Shop Product End -->
    </div>
</div>
<!-- Shop End -->
</div>

{% endblock content %}