ecommerce_app/urls.py
from django.urls import path, include
from ecommerce_app import views

app_name = 'ecommerce_app'

urlpatterns = [
    path('', views.index, name='home' ),
    path('blog-single/<int:pk>/', views.blog_single, name='blog-single' ),
    path('blog/', views.blog, name='blog' ),
    path('contact/', views.contact, name='contact' ),
    path('product-detail/<int:pk>/', views.product_detail, name='product-detail' ),
    path('add-review/<int:id>/', views.add_review, name='add-review'),
    path('product/', views.product, name='product' ),
    path('cart/', views.cart, name='cart' ),
    path('home-two/', views.home_two, name='home-two' ),
    path('home-three/', views.home_three, name='home-three' ),
    path('add-to-cart/', views.add_to_cart, name='add-to-cart'),
    path('search/', views.search_view, name='search'),
    path('delete-from-cart/', views.delete_item_from_cart, name='delete-from-cart'),
    path('update-cart/', views.update_from_cart, name='update_cart'),
    path('checkout/<oid>', views.checkout, name='checkout'),
    path('shipping-address/', views.address, name='shipping-address'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('save_checkout_info/', views.save_checkout_info, name='save_checkout_info'),
    # Add to Wishlist
    path('add-to-wishlist/', views.add_to_wishlist, name='add-to-wishlist'),
    
    # Add to Wishlist
    path('delete-from-wishlist/', views.delete_wishlist, name='delete-from-wishlist'),


    
    #Paypal Url
    path('paypal/', include('paypal.standard.ipn.urls')),
    
     path('payment-completed/<oid>/', views.paypal_completed_view, name='payment-completed'),
     path('payment-failed/', views.paypal_failed_view, name='payment-failed'),


#Customer Dashboard URls

path('dashboard/', views.customer_dashboard, name='seller_dashboard'),     
path('order-detail/<int:pk>/', views.order_detail, name='order-detail'),     
path('shipping-address/', views.address, name='shipping-address'),
path('chart/', views.chart, name='chart'),
    
    
    

    

]

selleradmin/urls.py
from django.urls import path
from selleradmin import views

app_name = 'selleradmin'

urlpatterns = [
    path('seller-dashboard/', views.dashboard, name='seller-dashboard'),
    path('products/', views.product, name='products'),
    path('add-product/', views.add_product, name='add-product'),
    path('edit-product/<id>/', views.edit_product, name='edit-product'),
    path('delete-product/<id>/', views.delete_product, name='delete-product'),
    path('orders/', views.orders, name='orders'),
    path('order-details/<int:id>/', views.orders_detail, name='order-detail'),
    path('change-status/<int:id>/', views.change_order_status, name='change-status'),
    path('shop-page/', views.shop_page, name='shop-page'),
    path('reviews/', views.reviews, name='reviews'),

   
]

urls.py
from django.contrib import admin
from django.urls import path, include
from ecommerce_app import views
from django.conf import settings  
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import set_language
from django.conf.urls.static import static  
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include('ecommerce_app.urls', namespace='ecommerce_app')),
      path('', include('userauth.urls', namespace='userauth')),
      path('', include('selleradmin.urls', namespace='selleradmin')),
  

]

urlpatterns += i18n_patterns(
    # your other urls
     
      path('i18n/setlang/', set_language, name='set_language'),
)
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)  

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  

userauth/urls.py
from django.urls import path
from userauth import views

app_name = 'userauth'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('change_password/', views.change_password, name='change_password'),

]

templates/dashboard/base2.html
{% load static %}

<!DOCTYPE html>
<html :class="{ 'theme-dark': dark }" x-data="data()" lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
    {% block title %}

    {% endblock title %}
    
    </title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap"
        rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'files/dashboard/assets/css/tailwind.output.css' %}" />
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
        integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="{% static 'drivers/assets/js/init-alpine.js' %}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" defer></script>
    <script src="{% static 'files/dashboard/assets/js/charts-lines.js' %}" defer></script>
    <script src="{% static 'files/dashboard/assets/js/charts-pie.js' %}" defer></script>
    <link rel="stylesheet" href="{% static 'files/dashboard/css/styles.min.css' %}" />

</head>

<body>
    <div class="page-wrapper mb-4 pb-3" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6"
        data-sidebartype="full" data-sidebar-position="fixed" >
        <aside class="left-sidebar">
            <!-- Sidebar scroll-->
            <div>
                <div class="brand-logo d-flex align-items-center justify-content-between">
                    <a href="./index.html" class="text-nowrap logo-img">
                        <img src="{% static 'files/dashboard/images/logos/dark-logo.svg' %}" width="180" alt="" />
                    </a>
                    <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
                        <i class="ti ti-x fs-8"></i>
                    </div>
                </div>
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
                    <ul id="sidebarnav">
                        <li class="nav-small-cap">
                            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                            <span class="hide-menu">Home</span>
                        </li>
                        <li class="sidebar-item mb-2">
                            <a class="sidebar-link" href="{% url 'selleradmin:seller-dashboard' %}"
                                aria-expanded="false">
                                <span>
                                    <i class="ti ti-layout-dashboard"></i>
                                </span>
                                <span class="hide-menu">Dashboard</span>
                            </a>
                        </li>

                      
                        <li class="sidebar-item">
                            <a class="sidebar-link" href="{% url 'selleradmin:products' %}" aria-expanded="false">
                                <span>
                                    <i class="ti ti-login"></i>
                                </span>
                                <span class="hide-menu">Product</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link" href="{% url 'selleradmin:orders' %}" aria-expanded="false">
                                <span>
                                    <i class="ti ti-login"></i>
                                </span>
                                <span class="hide-menu">Orders</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link" href="{% url 'selleradmin:shop-page' %}" aria-expanded="false">
                                <span>
                                    <i class="ti ti-login"></i>
                                </span>
                                <span class="hide-menu">Shop Page</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link" href="{% url 'selleradmin:add-product' %}" aria-expanded="false">
                                <span>
                                    <i class="ti ti-login"></i>
                                </span>
                                <span class="hide-menu">Add Product</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link" href="{% url 'selleradmin:reviews' %}" aria-expanded="false">
                                <span>
                                    <i class="ti ti-login"></i>
                                </span>
                                <span class="hide-menu">Reviews</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link" href="./authentication-register.html" aria-expanded="false">
                                <span>
                                    <i class="ti ti-user-plus"></i>
                                </span>
                                <span class="hide-menu">Register</span>
                            </a>
                        </li>
                        <li class="nav-small-cap">
                            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                            <span class="hide-menu">EXTRA</span>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link" href="./icon-tabler.html" aria-expanded="false">
                                <span>
                                    <i class="ti ti-mood-happy"></i>
                                </span>
                                <span class="hide-menu">Icons</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link" href="./sample-page.html" aria-expanded="false">
                                <span>
                                    <i class="ti ti-aperture"></i>
                                </span>
                                <span class="hide-menu">User Profile</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link" href="{% url 'ecommerce_app:shipping-address' %}"
                                aria-expanded="false">
                                <span>
                                    <i class="ti ti-aperture"></i>
                                </span>
                                <span class="hide-menu">Shipping Address</span>
                            </a>
                        </li>
                    </ul>
                    <div class="unlimited-access hide-menu bg-light-primary position-relative mb-7 mt-5 rounded">
                        <div class="d-flex">
                            <div class="unlimited-access-title me-3">
                                <h6 class="fw-semibold fs-4 mb-6 text-dark w-85">Upgrade to pro</h6>
                                <a href="https://adminmart.com/product/modernize-bootstrap-5-admin-template/"
                                    target="_blank" class="btn btn-primary fs-2 fw-semibold lh-sm">Buy Pro</a>
                            </div>
                            <div class="unlimited-access-img">
                                <img src="{% static 'files/dashboard/images/backgrounds/rocket.png' %}" alt=""
                                    class="img-fluid">
                            </div>
                        </div>
                    </div>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>
        <!--  Sidebar End -->
        <!--  Main wrapper -->
        <div class="body-wrapper">
            <!--  Header Start -->
            <header class="app-header">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <ul class="navbar-nav">
                        <li class="nav-item d-block d-xl-none">
                            <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse"
                                href="javascript:void(0)">
                                <i class="ti ti-menu-2"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav-icon-hover" href="javascript:void(0)">
                                <i class="ti ti-bell-ringing"></i>
                                <div class="notification bg-primary rounded-circle"></div>
                            </a>
                        </li>
                    </ul>
                    <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
                        <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">
                            <a href="https://adminmart.com/product/modernize-free-bootstrap-admin-dashboard/"
                                target="_blank" class="btn btn-primary">Download Free</a>
                            <li class="nav-item dropdown">
                                <a class="nav-link nav-icon-hover" href="javascript:void(0)" id="drop2"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                    <img src="{% static 'files/dashboard/images/profile/user-1.jpg' %}" alt=""
                                        width="35" height="35" class="rounded-circle">
                                </a>
                                <div class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up"
                                    aria-labelledby="drop2">
                                    <div class="message-body">
                                        <a href="{% url 'selleradmin:seller-dashboard' %}"
                                            class="d-flex align-items-center gap-2 dropdown-item">
                                            <i class="ti ti-user fs-6"></i>
                                            <p class="mb-0 fs-3">Admin Page</p>
                                        </a>
                                        <a href="{% url 'ecommerce_app:seller_dashboard' %}"
                                            class="d-flex align-items-center gap-2 dropdown-item">
                                            <i class="ti ti-mail fs-6"></i>
                                            <p class="mb-0 fs-3">My Account</p>
                                        </a>
                                        <a href="{% url 'ecommerce_app:home' %}"
                                            class="d-flex align-items-center gap-2 dropdown-item">
                                            <i class="ti ti-list-check fs-6"></i>
                                            <p class="mb-0 fs-3">View Site</p>
                                        </a>
                                        <a href="{% url 'userauth:logout' %}"
                                            class="btn btn-outline-primary mx-3 mt-2 d-block">Logout</a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
            </header>
        {% if messages %}
         {% for message in messages %}
           <div class="alert  mt-4 {{message.tags}}" >
                 <strong> {{ message }}  </strong> 
           </div>
         {% endfor %}

        {% endif %}

          <script>
          setTimeout(() => {
            $(".alert").alert("close")
          }, 3000) 

          </script>

    
  
        
        <!--  Row 1 -->
            <!--  Header End -->
            <!-- Sidebar Start -->
         {% block content %}

         {% endblock content %}
        </div>
    </div>
    <script src="{% static 'files/dashboard/libs/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'files/dashboard/libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'files/dashboard/js/sidebarmenu.js' %}"></script>
    <script src="{% static 'files/dashboard/js/app.min.js' %}"></script>
    <script src="{% static 'files/dashboard/libs/apexcharts/dist/apexcharts.min.js' %}"></script>
    <script src="{% static 'files/dashboard/libs/simplebar/dist/simplebar.js' %}"></script>
    <script src="{% static 'files/dashboard/js/dashboard.js' %}"></script>

</body>

</html>

templates/dashboard/index.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Modernize Free</title>
  <link rel="shortcut icon" type="image/png" href="{% static 'files/dashboard/images/logos/favicon.png' %}" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="{% static 'files/dashboard/css/styles.min.css' %}" />
</head>

<body>
  <!--  Body Wrapper -->
  <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
    data-sidebar-position="fixed" data-header-position="fixed">
    <!-- Sidebar Start -->
    <aside class="left-sidebar">
      <!-- Sidebar scroll-->
      <div>
        <div class="brand-logo d-flex align-items-center justify-content-between">
          <a href="./index.html" class="text-nowrap logo-img">
            <img src="{% static 'files/dashboard/images/logos/dark-logo.svg' %}" width="180" alt="" />
          </a>
          <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
            <i class="ti ti-x fs-8"></i>
          </div>
        </div>
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
          <ul id="sidebarnav">
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">Home</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'ecommerce_app:seller_dashboard' %}" aria-expanded="false">
                <span>
                  <i class="ti ti-layout-dashboard"></i>
                </span>
                <span class="hide-menu">Dashboard</span>
              </a>
            </li>
       
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">AUTH</span>
            </li>
            {% comment %} <li class="sidebar-item">
              <a class="sidebar-link" href="./authentication-login.html" aria-expanded="false">
                <span>
                  <i class="ti ti-login"></i>
                </span>
                <span class="hide-menu">Login</span>
              </a>
            </li> {% endcomment %}
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'userauth:change_password' %}" aria-expanded="false">
                <span>
                  <i class="ti ti-user-plus"></i>
                </span>
                <span class="hide-menu">Change Password</span>
              </a>
            </li>
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">EXTRA</span>
            </li>
            {% comment %} <li class="sidebar-item">
              <a class="sidebar-link" href="./icon-tabler.html" aria-expanded="false">
                <span>
                  <i class="ti ti-mood-happy"></i>
                </span>
                <span class="hide-menu">Spending Tracker</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="./sample-page.html" aria-expanded="false">
                <span>
                  <i class="ti ti-aperture"></i>
                </span>
                <span class="hide-menu">User Profile</span>
              </a>
            </li> {% endcomment %}
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'ecommerce_app:shipping-address' %}" aria-expanded="false">
                <span>
                  <i class="ti ti-aperture"></i>
                </span>
                <span class="hide-menu">Shipping Address</span>
              </a>
            </li>
          </ul>
          <div class="unlimited-access hide-menu bg-light-primary position-relative mb-7 mt-5 rounded">
            <div class="d-flex">
              <div class="unlimited-access-title me-3">
                <h6 class="fw-semibold fs-4 mb-6 text-dark w-85">Upgrade to pro</h6>
                <a href="https://adminmart.com/product/modernize-bootstrap-5-admin-template/" target="_blank" class="btn btn-primary fs-2 fw-semibold lh-sm">Buy Pro</a>
              </div>
              <div class="unlimited-access-img">
                <img src="{% static 'files/dashboard/images/backgrounds/rocket.png' %}" alt="" class="img-fluid">
              </div>
            </div>
          </div>
        </nav>
        <!-- End Sidebar navigation -->
      </div>
      <!-- End Sidebar scroll-->
    </aside>
    <!--  Sidebar End -->
    <!--  Main wrapper -->
    <div class="body-wrapper">
      <!--  Header Start -->
      <header class="app-header">
        <nav class="navbar navbar-expand-lg navbar-light">
          <ul class="navbar-nav">
            <li class="nav-item d-block d-xl-none">
              <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse" href="javascript:void(0)">
                <i class="ti ti-menu-2"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link nav-icon-hover" href="javascript:void(0)">
                <i class="ti ti-bell-ringing"></i>
                <div class="notification bg-primary rounded-circle"></div>
              </a>
            </li>
          </ul>
          <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
            <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">
              <a href="https://adminmart.com/product/modernize-free-bootstrap-admin-dashboard/" target="_blank" class="btn btn-primary">Download Free</a>
              <li class="nav-item dropdown">
                <a class="nav-link nav-icon-hover" href="javascript:void(0)" id="drop2" data-bs-toggle="dropdown"
                  aria-expanded="false">
                  <img src="{% static 'files/dashboard/images/profile/user-1.jpg' %}" alt="" width="35" height="35" class="rounded-circle">
                </a>
                <div class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up" aria-labelledby="drop2">
                  <div class="message-body">
                    <a href="{% url 'selleradmin:seller-dashboard' %}" class="d-flex align-items-center gap-2 dropdown-item">
                      <i class="ti ti-user fs-6"></i>
                      <p class="mb-0 fs-3">Admin Page</p>
                    </a>
                    <a href="{% url 'ecommerce_app:seller_dashboard' %}" class="d-flex align-items-center gap-2 dropdown-item">
                      <i class="ti ti-mail fs-6"></i>
                      <p class="mb-0 fs-3">My Account</p>
                    </a>
                    <a href="{% url 'ecommerce_app:home' %}" class="d-flex align-items-center gap-2 dropdown-item">
                      <i class="ti ti-list-check fs-6"></i>
                      <p class="mb-0 fs-3">View Site</p>
                    </a>
                    <a href="{% url 'userauth:logout' %}" class="btn btn-outline-primary mx-3 mt-2 d-block">Logout</a>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <!--  Header End -->
      <div class="container-fluid">
      <div class="alert alert-success">
      <h5>Welcome {{ request.user|title }}</h5>
      </div>
          {% if messages %}
         {% for message in messages %}
           <div class=" mt-4 alert {{message.tags}}" >
                 <strong> {{ message }} </strong> 
           </div>
         {% endfor %}

                {% endif %}
         <script>
          setTimeout(() => {
            $(".alert").alert("close")
          }, 3000)  
          </script>       
        <!--  Row 1 -->
      
        <div class="row">
       
          <div class="col-lg-12 my-4 d-flex align-items-stretch">
            <div class="card w-100">
              <div class="card-body p-4">
                <h5 class="card-title fw-semibold mb-4">YOur Orders</h5>
                <div class="table-responsive">
                  <table class="table text-nowrap mb-0 align-middle">
                    <thead class="text-dark fs-4">
                      <tr>
                        <th class="border-bottom-0">
                          <h6 class="fw-semibold mb-0">Orders</h6>
                        </th>
                        <th class="border-bottom-0">
                          <h6 class="fw-semibold mb-0">Date</h6>
                        </th>
                    
                        <th class="border-bottom-0">
                          <h6 class="fw-semibold mb-0">Status</h6>
                        </th>
                        
                        <th class="border-bottom-0">
                          <h6 class="fw-semibold mb-0">Paid Status</h6>
                        </th>

                        <th class="border-bottom-0">
                          <h6 class="fw-semibold mb-0">Total</h6>
                        </th>
                        <th class="border-bottom-0">
                          <h6 class="fw-semibold mb-0">Action</h6>
                        </th>

                        
                      </tr>
                    </thead>
                    <tbody>
                    {% for order in orders %}
                      <tr>
                        <td class="border-bottom-0"><h6 class="fw-semibold mb-0">#{{ order.id }}</h6></td>
                        <td class="border-bottom-0">
                            <h6 class="fw-semibold mb-1"></h6>
                            <span class="fw-normal">{{ order.order_date }}</span>                          
                        </td>
                      
                        <td class="border-bottom-0">
                          <div class="d-flex align-items-center gap-2">
                            <span class="badge bg-primary rounded-3 fw-semibold">{{ order.product_status }}</span>
                          </div>
                        </td>
                        {% if order.paid_status == True %}
                        <td class="border-bottom-0">
                          <p class="mb-0 fw-normal "><i class="fa-solid fa-check text-success"></i></p>
                        </td>
                        {% else %}
                         <td class="border-bottom-0">
                          <p class="mb-0 fw-normal "><i class="fa-solid fa-x text-danger"></i></p>
                        </td>
                        {% endif %}
                        <td class="border-bottom-0">
                          <h6 class="fw-semibold mb-0 fs-4">&#8358;{{ order.price }}</h6>
                        </td>
                        <td class="border-bottom-0">
                          <a href="{% url 'ecommerce_app:order-detail' order.id %}" class="fw-semibold mb-0 fs-4">View</a>
                        </td>
                        
                      </tr> 
                    {% endfor %}  
                                      
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
   
        <div class="py-6 px-6 text-center">
          <p class="mb-0 fs-4">Design and Developed by <a href="https://adminmart.com/" target="_blank" class="pe-1 text-primary text-decoration-underline">AdminMart.com</a> Distributed by <a href="https://themewagon.com">ThemeWagon</a></p>
        </div>
      </div>
    </div>
  </div>
  <script src="{% static 'files/dashboard/libs/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'files/dashboard/libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'files/dashboard/js/sidebarmenu.js' %}"></script>
  <script src="{% static 'files/dashboard/js/app.min.js' %}"></script>
  <script src="{% static 'files/dashboard/libs/apexcharts/dist/apexcharts.min.js' %}"></script>
  <script src="{% static 'files/dashboard/libs/simplebar/dist/simplebar.js' %}"></script>
  <script src="{% static 'files/dashboard/js/dashboard.js' %}"></script>
</body>

</html>